"""empty message

Revision ID: c99a187f0227
Revises: c9c0b02ceb7f
Create Date: 2025-11-27 19:15:07.074364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c99a187f0227'
down_revision: Union[str, Sequence[str], None] = 'c9c0b02ceb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'check_in',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.alter_column('members', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('members', 'join_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('members', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', name='memberstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('members', 'total_checkins',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plans', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plans', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.alter_column('members', 'total_checkins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('members', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('active', 'inactive', name='memberstatus'),
               nullable=True)
    op.alter_column('members', 'join_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('members', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.alter_column('attendance', 'check_in',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('attendance', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
